[features]
seeds = false
skip-lint = false
[programs.localnet]
solana = "AckSBrz9UShZJdzKBXAeUP9jX7AX9MPdR9RGrvzGwoXb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/forrust/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
